language: node_js
node_js:
- "0.10"

after_success:
  # Generate zip releases
  - grunt release

  # Submit coverage data to coveralls
  - grunt -f coveralls:core

  # Publish Bower repository
  - chmod +x build/scripts/bower-publish.sh
  - ./build/scripts/bower-publish.sh

  # Update gh-pages branch
  - chmod +x build/scripts/docs-update.sh
  - ./build/scripts/docs-update.sh

# Try to avoid problem with tag_name not well formed
# See travis-ci/travis-ci#2510 for reference
before_deploy:
  - git fetch --tags

deploy:
  provider: releases
  api-key: "${GH_TOKEN}"
  skip_cleanup: true
  file:
    - frontkit.zip
    - frontkit.dev.zip
  on:
    tags: true
    all_branches: true

notifications:
  slack: "${SLACK_ROOM}"
  email:
    on_success: change
    on_failure: always

env:
  global:
    - SAUCE_USERNAME: injoin

    # SAUCE_ACCESS_KEY
    - secure: YyhI+pQBi1QfS6OLoN/gwOB3oU/cPpuyFJ3oGpqlMFdQ8Ei60FfM1m7VE1KyfwrRLvbvH+RUisMz9AAQh9LyEEFkDVcicS1li/cVWSGFAJyMKlJZBcof0L+dZ7uwJxVdzewSHzM7pegnRGXfcxi3sVlsKnxrc7KVq7qKpg8CzoI=

    # COVERALLS_REPO_TOKEN
    - secure: dSLinYHNDWaueRbh/yKEUhlWt4y+Ygf1aCgtn5vfNbh2AOSRa+R1Sq4U1uinPKa5/vmoYbNahljM5Vk5u220EMuDtfGoZwy4m/TVMENcjP5T2zoDEGYMqB4hlL7D+9mzWgsO6TJkqtnUvxJq2A+TJaWKe2u+YuN4kgQ/koU8Zvo=

    # SLACK_ROOM
    - secure: rcSWhrsP4NoiEDAUFo33J9Q2GtdaPTSnFrGabnr/EsVHwczi+dCLorDmRwkk18Gw5ako/C1WHm5y6LpTF3mCc+tUwZUPqr3YCpAtVfHiyl7W9maMaq28bd8+4+NDKOByuSpyYkzfDcxiyokcnGjk3xNMAwWMKmKXP2GmuUt+tF4=

    # GH_TOKEN
    - secure: m2qLAV/cb2MraZ+9Mv9Cw7vMMZyJAIyXFvAo6ImQ9IPTgZOCV0ybdYJwVTJ1B5NyU93F7CTturSvlu1gsOiuyZR6xiDP6VYG1iErSbkYB6sFnjZh2HA7Hpey3rqNHjHnN9NdNQPJdKIPKyW/gyJOxz1Dy/7OWqkYpHb28ZC/niY=

    # bower_id_rsa_{00..30}
    - secure: 3w+MQ84esx9Nj6l9WAHPMboYUY1u8MlrhKX6HGY7XxrrGczX8aVnT3FnCKW8bml+odoaajktofAR4lW/zH0Len3ueh04b/FEn6pDk+0bBe1CifAfOfQpJqFGMkL75hhYFDJcF/8liaBbHIsdj6E92kGM7hymJqrE9JDXQdYeWlw=
    - secure: lIgl4q6xypHub27f/hsgjlhR0LTg4vwL4Yq891wGQ4J8ouZ1AJZ0GfdT2uUxxKoc/k+ApM3mZfK/7wQjjogXmbzeQNwifq3VB2x0irXnGj8DvwTmMEgARNe4p5nB35/+uQxIBJjJvDlB9Dv7wVxUJBxdeL3XWkCPliXjKRKV8Pc=
    - secure: EWQD1qDAFtDXQnEi2xdijdHTx0HiVF+YBKVWh2a3K1rWEBy/OSUKkOsiw3CApzx6ID3XTTAma0BF1bwk/tO33M6thDF4NDPLjSwrmtrT++AwIP7Suhak2RQC5Aw4TYawf4oGU5b52JwAuBQlFu0Xn/QUP4BQIkADCTuZ7Vn1PDo=
    - secure: M4TW43vLwjZhSIVG6aSgNnLav8eJDF84FVkVgTK49jilKQO3XVXN76JR5+ZmyHXe6awXSSoSGAq0iWg4nqgMR1L3eqRRM901AgFkcQtWJTjs3RRBjcFXEczFomQ+5DJJ/pIZoVdZHWWlEKmbQCWRbzOJIc796KE6DAAVpZjVhO0=
    - secure: NYIoUL0yFXLc914RnsOR46bDMtv10zUq9UfrK/rcI++aHiMtGCK8Fc9iGBUFIDBFxIiAAd6j/ZQsul7RlBvRO0M/kMaBWLAibkZBDmlX2CiJOy4qVPGEjLrs924OIWd6IKmaGjwvn2nrQK5wUcQbPKoOUZWQLIM36JaZepe5+c4=
    - secure: ht5b10pxWXzlYX1fznZMTyGcvjNbvjprwEOi9+tDzwHjDRPYug6gzFXoO/GvkBvtWbF0tTXDgxO16YJ9+XpO1E4kZ10RKXreHVQWNgv93oa+1c1ldoyCk3EdTNr5IqhGdQsVPLlVP33rvF/DWrmH59VmvRv53mBdMAQiyJ746Mo=
    - secure: sz31U8LqpX7QrNpudIcfZsQMzy8zCkvibJdyaGLwRhtFcEuu/1DDNSV+RzjIY5GNDe5tDbh+nbGLcMsH+/b4DSVI76PapiusafeOavuVfM3NRYl4NfmwJFGjD87JyYfD5GOMPkK1jpcOroMW4DIicAquznxMVVjUxcM3mju18sI=
    - secure: 28UqO785t1sMrpKS/hPsJ4QnbENOP/YTX6zbe//ZgFlIoSbLj8loHq9BJBinV/Im5GF8BeUfecv8sRLe+gWcIDrf6fwV9Qi7+7QejxeYyDfBPtH//LsjVLnGJ083OuNVc98Iyn58Vd6r6JYUIVLQj34tr6CYVfmgBuUj9Z2OEjE=
    - secure: k00yTW6u33SgPu+noGNmrfc7ZgWKK91pvUCupnpiFphEeCLd1cJHsJEdEYKkIF5KKFRwbTZc5nT+9bJikn6jSOmNjp5qMi0RN53qVM3nzq1o6dRT9eYa+k9S5JILgrSUP/j21vkUHJ9CsMwwzOG7/z0LydJ+oB4+b3e+40AQ2oQ=
    - secure: cDwtk0HuwbZGs/1vDvteOEtJ2VYuvqvUkVCR1wQDvQdDqTkBJFtsxPWsAUhwh9XAyfYnXswKLzUAM1TSpxXVPfFq8uLluEjOff9xvtHeXx0TCOUE0AM3mNqa+I7kj2q0Sr3r5QqPasHtWAXD0PJjVpypyxwsdU1PUnK/7ZMstNI=
    - secure: CHIYnnORv8bv9Oc1BcdcMJPca6KRHOHt6Wdq7pc2SgDubudJanPIznASgjFrZMhQqiXt+zxpXgaxvVyM8uYRV6CcdbpLnmwcLDHiTvM1smoWbN+5a+jPcMdSEQenYQQEaX34IaKZgDrd8QRgaPN/iN0sbA7yiM1uKkpYCo++7hU=
    - secure: w0vP7o2q8FjZDDwLN5ZanblSTaUkHpBF3U4VSdHm5niIOhoF0FUVeabQDkj4aZ5tgJAERZExWLv/rnvrkCFyHjmz9faypL1D3gBseFFTUh/URBzW6PaVKbfgqHSYuTe65h7O3yMp7SSt/EcAP4mdnQsa75iL2sz2iSYYvsFYRDA=
    - secure: PaUsjLC/RMopuTiJGhtzsoz76p9nXNl80GwrAuX+pm8ToUYV3a5HHC2w6bqIIxEVPiTXfSf/pNE6Bluc8eDMtgg5IP0r8WEB1KsHiaWlP5mxTchoWiwM89eBXuFRx0HB9tF4Dmo8kWB7MdOtHl5QyvnkCaYgjmmuuFa/6t1pFuQ=
    - secure: VtpNMK4cd7tvkSSA6lHSvnDqfgCPMxEV0owSI2xMRGvOBAWSO5IC03wAcXiWHDi48Mc08YUQ9wTUBGir7MXJxm8ZZKsUtwxzw7do4Po4iY2UH5yaxFghN208ecWoXDDxRHXdJthmXYyK6o8A5HP1UKAL/wMUintmfV+1vlicDDk=
    - secure: mwuh1uAoagpyiygOJEkSdg5mBESsyLlZMONaD3BKx2MV6RqqBMxABIwAbSR8+kAh8FBemh/LORmzUblyoVFt5cbPhyyVzkTcDBtG5RYB8BSAdNOFBm+qCx2fgrNeNoco3tC91OfnVgS7Ai5fpN/eg3J3dizRjRBZV5IDLJlfJ50=
    - secure: OzVzckthUNrPOOvxpRn+IXWKcW7SeKNcw9VoTvDdltpzkpWfx17nVYsqT0e4jNY6YMLVPXlSYGeXRMHE7b/S9Dn+LCOom1wSN4oGU7Dfz6Fo2447Iy2lxEybWy1bV+yXRqaGvOAlaGVSCruBXA0glXKpBZltWnL9YGOQBd9de9o=
    - secure: YyWF87wKz3ZMsGVLIhFLgT10pbuu43xWuKSXZOgv5VTH7gKmYDjg5RrJSiWOltTzGzP85dncoK8V0OPnpIZkzmxPPJXTlHLYO5FZddQTaLB4YMtuPdoQvbJHaRuK6+kHBcjH2kVmOBmyOJJ4Ex2VZs7r4M8LE7Di6BPnEUr0NR0=
    - secure: 1+FgpxDU1EfUJpY/CWzymM0cDp3E/H8+MMBkhSvxCpLz1l0YfUTZheuFs4es6wvpRMS7VA0d3agtktPrbPA5nhxCWeIdlWfEv6ceDTBeir4zhkL80sGGo3UCATWsMMCdSZKZETM1Wp4EbrajazF/I0KovDXJFdbKoGsuMWFruso=
    - secure: pV2F9V0ildRZOsy2j+ABxG/sqG2ls94pcMEkZ1slZBdCGM7LWuOSGKq0mnc82c1TM2QbSYqVP5HWZ+qB7QQ1qnrx9p6lOKD9hv/LDptdc1tRGuPw6e0dpfaRgHqPQDprnVdWwjB1wxU6jTR+eSOZO9+Ka6WJ4igiNscovhP1Qoc=
    - secure: qyDDbtFUYa5+PxsAa/BWXRv1Y3dSYHJnn+Nhx4wvUZ8iY5w9RaA5gACZ4OcV+I1aJX1x23W1x285VioNBm9aCLGln2kRu03HUlSTMTlifRdCDxph3pZhQVJrNR+omwr++7953JsvG7psh9jLJnL+8g35F/6ET7tq4URT6mHcPIM=
    - secure: yhaCnSJ6DzZJZd6sOQU1Rqpzg+9K4wywywKxX68zWnwnWR5+IJpGlsY6QsBFqj5VM6CNJypD7ZSZ2eFgay8ybw5+3ROxj1W2UjTMwx1zruD8oMDf7g5Nja1fVl+15LYQfsfRYHyDA61x/gXZHiVJ/keMy16EwXYQTt0fXaWxtqE=
    - secure: hOI2wGyISx3IFWjpKwORn5O1pLOjymU+v9WdivQ+izBvvPF9hDzlQQqCBLKv/x+XsO/4rkTjC4kjt1oKdh15YD5qoA3+YMpxQC0h0FFmqEp94JNaeXr7qRwQyYktXKOs6qKbuF9JsqvTMrWBRAjG3GpmJ2yIHAu4XyrugxpCFXU=
    - secure: 0fJfDsUrTDIat+NJa2fTo6VNMI/yYxWObJHohmbL0YJTMr5Bw2bEIvL7UCXj+DMGta+lRgmOUeWk5a2T8raKnhQSGo0NXRB9u2MFmzXY9TqhPoYP28n4dmwyWmL5/Gdb+ijmYX/zy/i4mZYTUNxK/RnKxM8U9GHes6+lWskcJi4=

    # self_id_rsa_{00..30}
    - secure: Bag982gTDwSzSxEUkSak81Kcq8sTVCO9S1cUnDn5lrECnVMuPRql7BmctNwlu1/WjhMCvGy3ZdBZSCxXODl7ZOa5G4LoZZsx54DZp9nEIJTGuOaUUBB7eSpE58/0Y6cjgxLwhKYc76t1GBQjOry8QZbc0CZmI4MbcCu6+CgaJg4=
    - secure: ZQHW9pSKFGbDOA+LMJFZsa6viCmetBi72ztfmfu/VMhAJuYZXYIV/UHzbhwCNta3ufflRoxIOZkuiuMhvfF/A4Q65MFoaIctHVx9RfQ/kF1Kek8deXOZD8cKpPbcGi9lkek2GUyQtxoNH0rjFdorPlp6yvs/OWfhKRIcnOCke1o=
    - secure: 3fwqPJlrIeff44Cho9aJ4q8ZxGi5Pk+vP/Aw3Fl04OoUPGn99aKBC0WkRDGwSuw7td1SxIjiV6ZhZFO7mJ3JTEVkfOjSxDsR+mYWuM2o5L89zdItgmvIZc2n3XZ3NYCIeEyhj0rLUaM/MmarQkffgGsDFev1HLLNSZjoQMUfMlc=
    - secure: DW6VLhx5NnNgT4wu3ILr0p0A9sNOD3OqaiHkN8mmLwCHPr9LuTHA5lNTf8azuUTQOJDnqSCYu6TzrPNtFiDFYNOhi/i9tT7slTeoExd50hSh4KZnoyT8gTWezZ932W/M8tnTSPIxtjKy6xjRWaqxdnVBewGWGcxdAA9dv5J9PMo=
    - secure: FQrHw8eiNDdW2bVB++BG7ITz063tbiF12c0/G+Ki4Wbu4VAxK31dUhG2+LITY599q+gvyoxLrnoFp9Cqg5l0XmMGh6f7fJ7e785KeulnNROaKiCM5uSy5dHnwdrn+DN5iNzVgUhTHRmfecJd86wkyQj6WCmxZVV9nPU/UidbHwg=
    - secure: wChhZgPksw76OQXF3e9ADDZ5w7FfSK3e5RX0YNkYu10NzjI+9SNC+RW7EUajvqf6GeRmxXOCW2JMccZNW8rpg5eRg2End5SKPcdbb+PKl+/k7ccOS6yPMRFO9xdA4oz23D/2e3JD9mv2U0AwfqhOsKVI0Yga3uc+D4hSOYJIVsQ=
    - secure: v7GI+XOiIQNPtp/iUSK9nLajqR2t1cqVCy0Gp1BxG2krUUVLD49yfkIgar6KQzTWSGTakAFE8aytTnqleEl0yKLossgo6MxxMH+ZQJJNoi6NNAiRQ4nz8qEstggxMPrONVoI3IqxYYhzbtgDnWxTvUGUGwk8n33pO3i2Qt0cbJA=
    - secure: WMkW8FJOMEA+RsIMJ41A3ph50XeAL2aRcxQUSeN+1iJzaCWbraCy486ab2jofNZJxl/XEfOZmGAutIEiPp1I0zQLsKA0uDzZ0n8Xtyd5ekARDnER9dZiUaTuGzsh+WZ/pS+ikcKG/6/G7hUUEm81K1H0wxDuDx5ylqnCagM3n5g=
    - secure: z7ie9uHQ2HXeVoiEE6mD4iFIYFIClNBX+a8g7oDVZtUrUBgtKI2/P7PLnVeZfNBOp8h0GCK8NggTAkIk1/DAyWsk7jLv/1i7tdh3ybfDNaYhVHR3T7Iu0CEq9gpBmYbyoSfDvL6xoBMmp9ZDxVwTKyEdIGM8vmcOJ8Mr3uCHsGc=
    - secure: nq7cTGjs3ISyZLAh/X0SModoHH9mCJedKoAYk2HQxCC7KyIjMm/bQVrFm0X5dsCGThQJo+ZdffXcHVAJozVgQ1dREKQov9FeyNuvsROEC/Q62fesXamUIW3m7OCOnvPXoRkcQGbug3k/dwvLx0DfsTHOntlg9COxArowpngBjDI=
    - secure: Mdbze+g9KapFQptV0DPi4M2mzPJR13YJbP3+Hd7NdfsK5fl2nZyHE9ho5zgRQb/vjv4MhGHj+aqK+6SwiyknWsdkILFX6MrF9fe557N7fEq69PTuR1I/akkhkc8xLw5A0i7IRzub10vISE6XQ6hI6vpxWGwz38zUQ3GCa9UilkA=
    - secure: kqFMUziHdGn+3tSfHQBH7rXzKNFRbOszBYHU3soTfzzk+2jfxPSvAggYOhmgT292DVypiOe0TdArH8vsrMSU6rpLnbQq0FRVkvQT5axGzsKSi04zE/jxCBh5l9GRzWMei3O0FPWKfT00B6SrOE39yCwDmPXKFCmXSTVVTU32gLM=
    - secure: bLyO6oULSZdH717/yEji4e+t1tYBsGOrm5yOZ/9MuYfRJzUctLtS2r+eRS8jQ5vBhS2F/WQVBlYQbmrMvH+VdO3oyMnv6f4UMIdDFVPBxu3YnZ2y8W8IGkTyxeZ0ae0irQrCXYVRs0PdjkGVhNrWAlGh5iHYvd7Qjc2GBNGCrus=
    - secure: BbrDfIHz4IOu3Y/yEh/tPlt63Jtkpxgioc6kWNEhjvVVqJaq1LesVnMHAQDMOfWyLg+xfJYD9W0m/5ibg7sejQEzAtsVpz+qJhft6nKBpTYdd4ehzYrcSV8O74gfzLeoy6zmmGqJcNRRrujM3AxTmrchTaUiPqx/t1qRhEX0/LA=
    - secure: Nh1axpD3foqbEduNZdJYoe5ZVC42jejDFWOyzq51BwFPCAdbrcrH/oIYwGWW1HcFZ6/1Z/mWcuiOQK2qntn83G8Hz6E/eTtAcDznzDOLiEmFkqtOZjoA+na5TrpG0gAhY3N3UjzIXxTofNJkzQjoD8ebfIgyOMVUfcz5NdPg8L0=
    - secure: oxMcx6CRqywCxWtyNGqSPSF4OX97myenSVCUS7FoGA0GE+aYl8s/pOk4rmuU98BMJOVo43n7xoZvjpS8VMqjrj4uqTcaNnlF+kFFCIveTi7i1LU2pYczHin2nviRw6jjDqfj3SPeyT8IogesNIsKvQNM4KXDBwRj963REUGtoo4=
    - secure: ugG7dIp2TOoHUJS5dNL8I9hHom7iRTFTGN4M/HAotowGJuqOl+G5ovyvmvFcXvMC73rNM/Cu/VqlqAudOh+LoqEal+CYAk5ipKDKHtZa/AyfUm//gWOSeeUdkABtsbGvCcgmX48vkS8FLx9RNOeIFhhHxIrX0qkEQd5GaqDPXg0=
    - secure: cLi45YDP82NRX9F0mL6lqUFEa8OQMfvc5v23b1HXgKizlUEdPUgaxqwX9BWg3VCzye70hmXyWIw/ueFnrRxW4CYwP3NdkLkzGaTP4eL1YIwqHTtm7aRdVofKyoelyw+u6htmsFe7A6O7IN55A5PzJjC5BvKLelM9kG09BMbLA7Y=
    - secure: ZKeBn+dLuISW8JH+2EFYNC06HGh97SQtSpUoABcODJ4vgiXtOas//kX6I3aMSbHtzVbZjmKcfYFLPkNxQGAFEZ8f0uImUrhhdi/kyPyb3uaNlSvGXGjRveyoy7aPCOoEFNl7e5KxGI6Ln3JFIRcO47aG6qirgXm+P4MOn9dCHwg=
    - secure: kMyP/cGx2DmBW3MojyeQzZXJA2O5yhKmRKFSLxH3jtr6HelKKicLBVDgR1sNhhaiKt8p2uqsog/XAblGStOWkc00DskGmbAPNg2ho0Kugtv3eMITE2YQdAEKmdmVc9eYuksFLsbYr2NN/uNck1uB1Gan0MJGhO19Pbhrq1WmEs4=
    - secure: T9izOZfQgOEBqrlCEVdSYWrEF5vWuPhWVbeR3nY94bGXh5prNN6/TQE8MWhNWZXsW+XOfj85JVApUXHLDdEoYakXMUR5iqdAY6H09mEXx1/paLJRIGR+xolZSFlu5rIOE82h5CLUT7kt1OULJ1jmlSA99xvMX++PtIxeO3DF47g=
    - secure: c2ogck39Nt09xaPuiTHLP+mPEao2goQCXK4G186sckHeEpU1/izlnitC/TpRQh+CA3VjRl0RQbVDLEryofMNG9gHVuBzP/GX7cI6tFODzmknYz6fIf/L2WIz76N1qHE/Wj1ICMAgYL09ka8E4FGVJJde6dfq7TTDU7pw6pH89PM=
    - secure: d8YG1qKMkh5KOIUOlfiylnJcKHjQUcsweEqoVDr59zTYyzMTQe4rUOdHntMaYKmFyYnT0qiDbPVCcfnDWOWjbFEOTP/XaQoUtzKV79W97ElVCmAUrn41xr+KaZkBL8TNXVv6HAdZlXTUGAGM7D9BcUp4mbYPnaxdqK7YG5HMi1M=